name: Publish Gatsby Blog

on:
  push:
    branches: 
      - docs

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git checkout docs
    # - name: checkout branch
    #   run: |
    #     git checkout docs
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build
      run: |
        npm install
        npm run build
    - name: replace master
      run: |
        git checkout master
        cp -r ./public/* ./
        git add .
        git commit -m 'update page'
        git push

