name: Publish Gatsby Blog

on:
  push:
    branches:
      - docs

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git checkout docs
    # - name: checkout branch
    #   run: |
    #     git checkout docs
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build
      run: |
        npm install
        npm run build
    - name: replace master
      env:
        USER_EMAIL: ${{ secrets.USER_EMAIL }}
        USER_NAME: ${{ secrets.USER_NAME }}
        REMOTE_ORIGIN_URL: https://${{ secrets.USER_NAME }}:${{ secrets.PASSPORD }}@github.com/hannq/hannq.github.io.git
      run: |
        git config --global user.email $USER_EMAIL
        git config --global user.name $USER_NAME
        git checkout master
        npm install
        npm run clean
        git add .
        git commit -m 'clear old page'
        git push $REMOTE_ORIGIN_URL
        cp -r ./public/* ./
        git add .
        git commit -m 'update new page'
        git push $REMOTE_ORIGIN_URL

